{{- if .Values.pvc }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-postgres-pv
  labels:
    app: {{ .Release.Name }}-postgres
spec:
  capacity:
    storage: {{ .Values.pvc.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/raid5_mount/postgres/backups
    type: DirectoryOrCreate
{{- end }}
