apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  KAFKA_ADVERTISED_HOST_NAME: {{ .Values.configMap.KAFKA_ADVERTISED_HOST_NAME | quote }}
  KAFKA_PORT: {{ .Values.configMap.KAFKA_PORT | quote }}
  KAFKA_ZOOKEEPER_CONNECT: {{ .Values.configMap.KAFKA_ZOOKEEPER_CONNECT | quote }}
  KAFKA_MESSAGE_MAX_BYTES: {{ .Values.configMap.KAFKA_MESSAGE_MAX_BYTES | quote }}
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: {{ .Values.configMap.KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR | quote }}
  KAFKA_CREATE_TOPICS: {{ .Values.configMap.KAFKA_CREATE_TOPICS | quote }}