{{- if .Values.pgDeployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    app: {{ .Release.Name }}-postgres
spec:
  replicas: {{ .Values.pgDeployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      containers:
        - name: {{ .Release.Name }}-postgres
          image: {{ .Values.pgDeployment.image.repository }}:{{ .Values.pgDeployment.image.tag }}
          ports:
              - containerPort: {{ .Values.pgDeployment.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-pg-conf
          resources:
            requests:
              cpu: {{ .Values.pgDeployment.resources.requests.cpu }}
              memory: {{ .Values.pgDeployment.resources.requests.memory }}
            limits:
              cpu: {{ .Values.pgDeployment.resources.limits.cpu }}
              memory: {{ .Values.pgDeployment.resources.limits.memory }}
          {{ if .Values.pgPVC }}
          volumeMounts:
            - name: {{ .Release.Name }}-postgres
              mountPath: /var/lib/postgresql/data
          {{ end }}
      {{ if .Values.pgPVC }}
      volumes:
        - name: {{ .Release.Name }}-postgres
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-postgres-pvc
      {{ end }}
{{- end}}