{{- if .Values.pgPVC }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres-pvc
  labels:
    app: {{ .Release.Name }}-postgres
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  resources:
    requests:
      storage: {{ .Values.pgPVC.storage }}
  accessModes:
    - ReadWriteOnce
{{- end }}
