{{- if .Values.pgService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  selector:
    app: {{ .Release.Name }}-postgres
  ports:
    - protocol: TCP
      port: {{ .Values.pgService.port }}
      targetPort: {{ .Values.pgService.targetPort }}
{{- end}}