apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  MINIO_ROOT_USER: {{ .Values.configMap.MINIO_ROOT_USER | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.configMap.MINIO_ROOT_PASSWORD | quote }}