apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: {{ .Values.deployment.container.image.repository }}:{{ .Values.deployment.container.image.tag }}
          ports:
            - containerPort: {{ .Values.deployment.container.containerPorts.api.containerPort }}
            - containerPort: {{ .Values.deployment.container.containerPorts.console.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
          resources:
            requests:
              cpu: {{ .Values.deployment.resources.requests.cpu }}
              memory: {{ .Values.deployment.resources.requests.memory }}
            limits:
              cpu: {{ .Values.deployment.resources.limits.cpu }}
              memory: {{ .Values.deployment.resources.limits.memory }}
          {{ if .Values.minioPVC }}
          volumeMounts:
            - name: minio-storage
              mountPath: /data
          {{ end }}
      {{ if .Values.minioPVC }}
      volumes:
        - name: minio-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
      {{ end }}