apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
    - name: api
      protocol: TCP
      port: {{ .Values.service.ports.api.port }}
      targetPort: {{ .Values.service.ports.api.targetPort }}
    - name: console
      protocol: TCP
      port: {{ .Values.service.ports.console.port }}
      targetPort: {{ .Values.service.ports.console.targetPort }}