apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres-deployment
  labels:
    app: {{ .Release.Name }}-postgres
spec:
  replicas: {{ .Values.pgDeployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      containers:
        - name: {{ .Release.Name }}-postgres
          image: {{ .Values.pgDeployment.image.repository }}:{{ .Values.pgDeployment.image.tag }}
          ports:
              - containerPort: {{ .Values.pgDeployment.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-pg-conf